# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [5]:
s.split(' ')

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [11]:
print('The diameter of {0} is  {1} kilometers' .format(planet,diameter))

The diameter of Earth is  12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [16]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [36]:
arr=np.zeros(10,int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
arr=np.ones(10,int)
arr*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [39]:
arr=np.arange(20,35,2)
arr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [47]:
arr=np.arange(0,9)
new_arr=arr.reshape(3,3)
new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [56]:
a=np.array([1,2,3])
b=np.array([4,5,6])
new=np.concatenate((a,b))
new

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [57]:
import pandas as pd


In [63]:
data={'Name':['Ram','Sam','Guna'],'Mark':[45,23,89]}
a=pd.DataFrame(data)
a

Name  Mark
0   Ram    45
1   Sam    23
2  Guna    89

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [70]:
df= pd.date_range(start='1/1/2023' ,end='10/02/2023')
ser=pd.Series(df)
ser

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...    
270   2023-09-28
271   2023-09-29
272   2023-09-30
273   2023-10-01
274   2023-10-02
Length: 275, dtype: datetime64[ns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [71]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [73]:
pd.DataFrame(lists,columns=['S.no','Name','id'])

S.no Name  id
0     1  aaa  22
1     2  bbb  25
2     3  ccc  24